# sudo: false

language: cpp

os:
  - linux
  - osx

env:
  global:
    - STORAGE_HOSTNAME=frs.sourceforge.net
    - VERSION=1.0.0

matrix:
  include:
    - os: linux
      compiler: gcc
      env: UPLOAD_BUILD=1
    - os: linux
      compiler: clang
      env: UPLOAD_BUILD=0
    - os: osx
      compiler: clang
      env: UPLOAD_BUILD=1
    - os: osx
      compiler: gcc
      env: UPLOAD_BUILD=0
  exclude:
    - os: osx
      compiler:
      env:
    - os: linux
      compiler:
      env:

addons:
  ssh_known_hosts:
    - ${STORAGE_HOSTNAME}
  apt:
    sources:
      - wily
      - ubuntu-sdk-team
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
      - fakeroot
      - libimobiledevice-dev
      - libimobiledevice-utils
      - g++-5
      - clang-3.6
      - lintian

before_install:
  - pwd
  - ls -al
  - openssl aes-256-cbc -K $encrypted_59f5247592cb_key -iv $encrypted_59f5247592cb_iv -in ci-scripts/secrets.tar.enc -out secrets.tar -d
  - uname -a;
  - if [ $TRAVIS_OS_NAME = linux ]; then
        cat /etc/*release;
        cat /proc/cpuinfo;
        tar xvf secrets.tar -C /home/travis/.ssh/;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        brew update;
        ci-scripts/fix_brew.sh;
        tar xvf secrets.tar -C /Users/travis/.ssh/;
    fi;
  - $CXX --version;
  - set -e;

install:
  - ls -al ~;
    ls -al ~/.ssh;
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get install -y --force-yes --no-install-suggests --no-install-recommends libimobiledevice-dev libimobiledevice-utils;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        ls -al /Applications;
        cat ~/.ssh_host_rsa_key.pub;

        brew install -v android-platform-tools libimobiledevice libusb p7zip qt5;

        echo "${PATH}";
        QTDIR=$(brew info qt5 | grep '/Cellar/' | awk '{print $1}');
        PATH="${QTDIR}/bin:${PATH}";
        echo "${PATH}";
        ls -l "${QTDIR}";
        ls -l "${QTDIR}/bin";
    fi;

script:
  - source ci-scripts/set_env.sh;
  - cd "${PROGRAMNAME}";
  - if [ $TRAVIS_OS_NAME = linux ]; then
        if [ $CXX = "g++" ]; then
            qmake -spec linux-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec linux-clang;
        fi;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        if [ $CXX = "g++" ]; then
            qmake -spec macx-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec macx-clang;
        fi;
    fi;
  - echo "${PATH}";
  - make -j2;
  - cd ..;
  - ls -l "${PROGRAMNAME}";
  - if [ $TRAVIS_OS_NAME = linux ]; then
        strip --remove-section=.comment "${PROGRAMNAME}/${PROGRAMNAME}";
        file "${PROGRAMNAME}/${PROGRAMNAME}";
        ldd "${PROGRAMNAME}/${PROGRAMNAME}";

        export OUTPUT_FILENAME="${OUTPUT_DIRECTORY}.deb";
        ./ci-scripts/build_deb.sh;
        lintian -i -I --show-overrides "${OUTPUT_FILENAME}" && echo ok || echo failed;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        function copy_3rdparty() {
            THIRD_PARTY_NAME="$1";
            THIRD_PARTY_DIR="$2";
            PROGRAM_DIR=$(brew info "${THIRD_PARTY_NAME}" | grep '/Cellar/' | awk '{print $1}');
            cp -rv "${PROGRAM_DIR}" "${THIRD_PARTY_DIR}/${THIRD_PARTY_NAME}";
        };
        file "${PROGRAMNAME}/${PROGRAMNAME}.app/Contents/MacOS/${PROGRAMNAME}";
        THIRD_PARTY_DIR="${PROGRAMNAME}/${PROGRAMNAME}.app/Contents/MacOS/3rdparty";
        mkdir "${THIRD_PARTY_DIR}";
        copy_3rdparty android-platform-tools "${THIRD_PARTY_DIR}";
        copy_3rdparty libimobiledevice "${THIRD_PARTY_DIR}";

        mkdir "${OUTPUT_DIRECTORY}";
        mv "${PROGRAMNAME}/${PROGRAMNAME}.app" "${OUTPUT_DIRECTORY}/${PROGRAMNAME}.app";
        export OUTPUT_FILENAME="${OUTPUT_DIRECTORY}.zip";
        7z a -mx=9 "${OUTPUT_FILENAME}" "${OUTPUT_DIRECTORY}";
    fi
  - ls -l;

after_success:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        MD5_SUM=$(md5sum "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA1_SUM=$(sha1sum "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA512_SUM=$(sha512sum "${OUTPUT_FILENAME}" | awk '{print $1}');
    elif [ $TRAVIS_OS_NAME = osx ]; then
        MD5_SUM=$(md5 "${OUTPUT_FILENAME}" | awk '{print $4}');
        SHA1_SUM=$(shasum -a 1 "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA512_SUM=$(shasum -a 512 "${OUTPUT_FILENAME}" | awk '{print $1}');
    fi;
  - echo -n "md5 "; echo "${MD5_SUM}";
    echo -n "sha1 "; echo "${SHA1_SUM}";
    echo -n "sha512 "; echo "${SHA512_SUM}";
  - if [ $UPLOAD_BUILD = 1 ]; then
        OS_NAME="${TRAVIS_OS_NAME}";
        if [ $OS_NAME = "linux" ]; then
            OS_NAME="ubuntu";
        fi;
        scp -B -v -o "StrictHostKeyChecking no" "${OUTPUT_FILENAME}" "${STORAGE_USER_AND_PATH}/${OS_NAME}/";
    fi;

# vim: textwidth=0
