language: cpp
compiler:
  #- clang
  - gcc

os:
  - linux

env:
  global:
    secure: n0nANhPJX/N32Rnns0e3Oc2dje24iZl25oPo+hSUC1cho4jl3LE+CwZUy1BH72lw9Xbve/R2k9BfkInstGD0dyeNS2Fi5nfSFQwYnFvAa7N2G/AMrwI+OeUgiZEwCZ2o6qcDaKTa95PTkKgvk4bkN2zNjUvCS7bjUz0o6TFRWCA=
    secure: V1c8Stzln65jOb2OFKadvy5n4Y3Wv15iqsPr5gsXO7bQUexycbiCnLy8czhQiNJo+DS0zU+SGetq4sem9I35oGaamvf22QGmRMPQ94ogm7zuuRFdhXJX35/IgA5OcNTeezk/YHSNJTvqrjrl+RcsNFPQi7O2aQzVDWqkmTMmUTo=

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        cat /etc/*release;
        uname -a;
        cat /proc/cpuinfo;

        sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa;
        sudo apt-get update -qq;
    fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev;
        sudo apt-get install qt5-default qttools5-dev-tools;
        sudo apt-get install fakeroot;

        if [ "$CXX" = "g++" ]; then
            sudo apt-get install -qq g++-4.8;
        fi;

        if [ "$CXX" == "clang++" ]; then
            sudo apt-get install -qq clang-3.4;
        fi;
    fi


script:
  - $CXX --version;
    if [ $TRAVIS_OS_NAME = linux ]; then
        cd qdevicemonitor;

        if [ "$CXX" = "g++" ]; then
            qmake -spec linux-g++;
        fi;
        if [ "$CXX" = "clang++" ]; then
            qmake -spec linux-clang;
        fi;

        make -j2;

        cd ..;
        ./build_deb.sh;
        ls -l;
    fi

after_success:
  "curl --ftp-create-dirs -T *.deb -u $FTP_USER:$FTP_PASSWORD ftp://qdevicemonitor.uhostall.com/ubuntu/"

# vim: textwidth=0
