# sudo: false

language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - STORAGE_HOSTNAME=frs.sourceforge.net

addons:
  ssh_known_hosts:
    - ${STORAGE_HOSTNAME}
  apt:
    sources:
      - wily
      - ubuntu-sdk-team
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      - qt5-default
      - qttools5-dev-tools
      - fakeroot
      - libimobiledevice-dev
      - libimobiledevice-utils
      - g++-5
      - clang-3.6

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_install:
  - pwd
  - ls -al
  - openssl aes-256-cbc -K $encrypted_59f5247592cb_key -iv $encrypted_59f5247592cb_iv -in id_rsa.pub.enc -out /home/travis/.ssh/id_rsa.pub -d
  - openssl aes-256-cbc -K $encrypted_59f5247592cb_key -iv $encrypted_59f5247592cb_iv -in id_rsa.enc -out /home/travis/.ssh/id_rsa -d
  - uname -a;
  - if [ $TRAVIS_OS_NAME = linux ]; then
        cat /etc/*release;
        cat /proc/cpuinfo;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        brew update;
        ci-scripts/fix_brew.sh;
    fi;
  - $CXX --version;

install:
  - ls -al ~;
    ls -al ~/.ssh;
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get install -y --force-yes --no-install-suggests --no-install-recommends libimobiledevice-dev libimobiledevice-utils;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        set -e;

        ls -al /Applications;
        cat ~/.ssh_host_rsa_key.pub;

        brew install -v android-platform-tools libimobiledevice libusb p7zip qt5;

        echo "${PATH}";
        QTDIR=$(brew info qt5 | grep '/Cellar/' | awk '{print $1}');
        PATH="${QTDIR}/bin:${PATH}";
        echo "${PATH}";
        ls -l "${QTDIR}";
        ls -l "${QTDIR}/bin";
    fi;

script:
  - source ci-scripts/set_env.sh;
  - cd "${PROGRAMNAME}";
  - if [ $TRAVIS_OS_NAME = linux ]; then
        if [ $CXX = "g++" ]; then
            qmake -spec linux-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec linux-clang;
        fi;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        set -e;
        if [ $CXX = "g++" ]; then
            qmake -spec macx-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec macx-clang;
        fi;
    fi;
  - echo "${PATH}";
  - make -j2;
  - cd ..;
  - ls -l "${PROGRAMNAME}";
  - if [ $TRAVIS_OS_NAME = linux ]; then
        file "${PROGRAMNAME}/${PROGRAMNAME}";
        export OUTPUT_FILENAME="${OUTPUT_DIRECTORY}.deb";
        ./ci-scripts/build_deb.sh;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        function copy_3rdparty() {
            THIRD_PARTY_NAME="$1";
            THIRD_PARTY_DIR="$2";
            PROGRAM_DIR=$(brew info "${THIRD_PARTY_NAME}" | grep '/Cellar/' | awk '{print $1}');
            cp -rv "${PROGRAM_DIR}" "${THIRD_PARTY_DIR}/${THIRD_PARTY_NAME}";
        };
        file "${PROGRAMNAME}/${PROGRAMNAME}.app/Contents/MacOS/${PROGRAMNAME}";
        THIRD_PARTY_DIR="${PROGRAMNAME}/${PROGRAMNAME}.app/Contents/MacOS/3rdparty";
        mkdir "${THIRD_PARTY_DIR}";
        copy_3rdparty android-platform-tools "${THIRD_PARTY_DIR}";
        copy_3rdparty libimobiledevice "${THIRD_PARTY_DIR}";

        mkdir "${OUTPUT_DIRECTORY}";
        mv "${PROGRAMNAME}/${PROGRAMNAME}.app" "${OUTPUT_DIRECTORY}/${PROGRAMNAME}.app";
        export OUTPUT_FILENAME="${OUTPUT_DIRECTORY}.zip";
        7z a -mx=9 "${OUTPUT_FILENAME}" "${OUTPUT_DIRECTORY}";
    fi
  - ls -l;

after_success:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        MD5_SUM=$(md5sum "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA1_SUM=$(sha1sum "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA512_SUM=$(sha512sum "${OUTPUT_FILENAME}" | awk '{print $1}');

        set -e;
        scp -B -v -o "StrictHostKeyChecking no" "${OUTPUT_FILENAME}" "${STORAGE_USER_AND_PATH}/ubuntu/";
    elif [ $TRAVIS_OS_NAME = osx ]; then
        MD5_SUM=$(md5 "${OUTPUT_FILENAME}" | awk '{print $4}');
        SHA1_SUM=$(shasum -a 1 "${OUTPUT_FILENAME}" | awk '{print $1}');
        SHA512_SUM=$(shasum -a 512 "${OUTPUT_FILENAME}" | awk '{print $1}');

        set -e;
        scp -B -v -o "StrictHostKeyChecking no" "${OUTPUT_FILENAME}" "${STORAGE_USER_AND_PATH}/osx/";
    fi;
  - echo "md5: ${MD5_SUM}";
  - echo "sha1: ${SHA1_SUM}";
  - echo "sha512: ${SHA512_SUM}";

# vim: textwidth=0
