language: cpp
compiler:
  - gcc
  #- clang

os:
  #- linux
  - osx

env:
  global:
    - secure: "n0nANhPJX/N32Rnns0e3Oc2dje24iZl25oPo+hSUC1cho4jl3LE+CwZUy1BH72lw9Xbve/R2k9BfkInstGD0dyeNS2Fi5nfSFQwYnFvAa7N2G/AMrwI+OeUgiZEwCZ2o6qcDaKTa95PTkKgvk4bkN2zNjUvCS7bjUz0o6TFRWCA="
    - secure: "fiDJGTfJm+4DP1GkgqmqifVYTDrURb/1r+Flx7OVwY7zbqs4xKfHkf2zDjqcFNyHeSj4+ekqba7x+5zKyjDuC9QNlSu4dZPrDyjLBxA262CHQLqYvP0FdG0aNjR3/PBMqUDPzsY0If26n7xlzJRlAJv5mFpwx0mya46UnTIrpIk="

before_install:
  - uname -a;

    if [ $TRAVIS_OS_NAME = linux ]; then
        cat /etc/*release;
        cat /proc/cpuinfo;

        sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa;
        sudo apt-get update -qq;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        brew update;
    fi;

    $CXX --version;

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev;
        sudo apt-get install qt5-default qttools5-dev-tools;
        sudo apt-get install fakeroot;

        if [ $CXX = "g++" ]; then
            sudo apt-get install -qq g++-4.8;
        fi;

        if [ $CXX = "clang++" ]; then
            sudo apt-get install -qq clang-3.4;
        fi;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        function checksum_sha1() {
            OUR_CHECKSUM=$(openssl sha1 "$1" | cut -d " " -f 2);
            ORIG_CHECKSUM=$(grep -o '^[0-9a-f]*' "$2");
            echo "${OUR_CHECKSUM}";
            echo "${ORIG_CHECKSUM}";
            if [ "${OUR_CHECKSUM}" == "${ORIG_CHECKSUM}" ]; then
                echo 'checksum is ok';
            else
                exit 1;
            fi;
        };

        QT_DISTRO_MOUNTPOINT="qt-opensource-mac-x64-clang-5.4.0";
        QT_DISTRO_FILE="${QT_DISTRO_MOUNTPOINT}.dmg";
        QT_DISTRO_SHA1_FILE="${QT_DISTRO_FILE}.sha1";
        QT_DISTRO_URL="http://download.qt.io/official_releases/qt/5.4/5.4.0/";

        wget -c --timeout=30 --tries=10 "${QT_DISTRO_SHA1_FILE}";
        wget -c --timeout=30 --tries=10 "${QT_DISTRO_URL}/${QT_DISTRO_FILE}";
        checksum_sha1 "${QT_DISTRO_URL}/${QT_DISTRO_FILE}" "${QT_DISTRO_URL}/${QT_DISTRO_SHA1_FILE}";

        hdiutil attach "${QT_DISTRO_FILE}";
        ls -l "/Volumes";
        ls -lR "/Volumes/${QT_DISTRO_MOUNTPOINT}";
        hdiutil eject "/Volumes/${QT_DISTRO_MOUNTPOINT}";
    fi;


script:
  - cd qdevicemonitor;

    if [ $TRAVIS_OS_NAME = linux ]; then
        if [ $CXX = "g++" ]; then
            qmake -spec linux-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec linux-clang;
        fi;
        ./ci-scripts/build_deb.sh;
    elif [ $TRAVIS_OS_NAME = osx ]; then
        if [ $CXX = "g++" ]; then
            qmake -spec macx-g++;
        fi;
        if [ $CXX = "clang++" ]; then
            qmake -spec macx-clang;
        fi;
    fi;

    make -j2;
    cd ..;
    ls -l qdevicemonitor;
    file qdevicemonitor/qdevicemonitor;

    ls -l;

after_success:
  - if [ $TRAVIS_OS_NAME = linux ]; then
        curl --ftp-create-dirs -T *.deb -u $FTP_USER:$FTP_PASSWORD ftp://qdevicemonitor.uhostall.com/ubuntu/ ;
    fi;

# vim: textwidth=0
