version: 0.0.{build}

os: unstable

install:
  - ci-scripts\set_env.bat
  - echo %OUTPUT_DATETIME%
  - echo %OUTPUT_DIRECTORY%
  - echo %OUTPUT_FILENAME%
  - dir C:\
  - dir C:\Qt
  - dir C:\cygwin
  - dir C:\cygwin\home
  - dir %QTDIR%\
  - dir %QTDIR%\lib
  - dir %QTDIR%\bin
  - dir %MINGW%\bin
  - dir "C:\Program Files"
  - dir "C:\Program Files (x86)"
  - '%CYG_ROOT%\setup-x86.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl -P libusb1.0 -P libusb1.0-devel -P libxml2 -P libxml2-devel -P openssl-devel -P dos2unix'
  - copy ci-scripts\download_and_build_libimobiledevice.sh "%CYG_HOMEDIR%"
  - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin && export HOME=/home/appveyor && cd $HOME && ./download_and_build_libimobiledevice.sh"'

build_script:
  - cd %PROGRAMNAME%
  - qmake
  - mingw32-make -j4
  - dir release
  - cd ..
  - mkdir "%OUTPUT_DIRECTORY%"
  - cd "%OUTPUT_DIRECTORY%"
  - mkdir "platforms"
  - copy "%QTDIR%\bin\libgcc_s_dw2-1.dll" .
  - copy "%QTDIR%\bin\libstdc++-6.dll" .
  - copy "%QTDIR%\bin\libwinpthread-1.dll" .
  - copy "%QTDIR%\bin\icuin52.dll" .
  - copy "%QTDIR%\bin\icuuc52.dll" .
  - copy "%QTDIR%\bin\icudt52.dll" .
  - copy "%QTDIR%\bin\Qt5Core.dll" .
  - copy "%QTDIR%\bin\Qt5Gui.dll" .
  - copy "%QTDIR%\bin\Qt5Widgets.dll" .
  - copy "%QTDIR%\plugins\platforms\qwindows.dll" platforms\
  - move "..\%PROGRAMNAME%\release\%PROGRAMNAME%.exe" .
  - move "%CYG_HOMEDIR%\3rdparty" .
  - cd ..
  - 7z a -mx=9 "%OUTPUT_FILENAME%" "%OUTPUT_DIRECTORY%"

artifacts:
  - path: $(OUTPUT_FILENAME)
    name: QDeviceMonitor

# vim: textwidth=0
