version: "1.0.1 build {build}"

# os: unstable

environment:
  global:
    VERSION: 1.0.1

install:
  - ci-scripts\set_env.bat
  - echo %OUTPUT_DATETIME%
  - echo %OUTPUT_DIRECTORY%
  - echo %OUTPUT_FILENAME%
  - dir C:\
  - dir C:\Qt
  - dir %QTDIR%\
  - dir %QTDIR%\lib
  - dir %QTDIR%\bin
  - dir %QTDIR%\plugins
  - dir %QTDIR%\plugins\platforms
  - dir %MINGW%\bin
  - dir %CYG_ROOT_WIN%
  - dir %CYG_ROOT_WIN%\bin
  - dir "C:\Program Files"
  - dir "C:\Program Files (x86)"
  - del /Q %CYG_ROOT_WIN%\%CYG_INSTALLER%
  - ps: Start-FileDownload 'http://www.cygwin.com/setup-x86.exe' -FileName 'C:\cygwin\setup-x86.exe'
  - '%CYG_ROOT%\%CYG_INSTALLER% -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P autoconf -P automake -P bison -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl -P libusb1.0 -P libusb1.0-devel -P libxml2 -P libxml2-devel -P openssl-devel -P dos2unix'
  - perl -V
  - copy ci-scripts\download_and_build_libimobiledevice.sh "%CYG_HOMEDIR%"
  - copy ci-scripts\*.patch "%CYG_HOMEDIR%"
  - '%CYG_ROOT%/bin/bash -lc "set -v -x ; cygcheck -dc cygwin ; cd /tmp && ./download_and_build_libimobiledevice.sh"'

build_script:
  - mkdir "%OUTPUT_DIRECTORY%"
  - cd "%OUTPUT_DIRECTORY%"
  - mkdir "platforms"
  - copy "%QTDIR%\bin\libgcc_s_dw2-1.dll" .
  - copy "%QTDIR%\bin\libstdc++-6.dll" .
  - copy "%QTDIR%\bin\libwinpthread-1.dll" .
  - copy "%QTDIR%\bin\Qt5Core.dll" .
  - copy "%QTDIR%\bin\Qt5Gui.dll" .
  - copy "%QTDIR%\bin\Qt5Widgets.dll" .
  - copy "%QTDIR%\plugins\platforms\qwindows.dll" platforms\
  - move "%CYG_HOMEDIR%\3rdparty" .
  - cd ..
  - cd "%PROGRAMNAME%\tests"
  - qmake
  - mingw32-make -j4
  - dir
  - debug\tests
  - cd ..
  - set PKG_CONFIG_PATH="..\%OUTPUT_DIRECTORY%\3rdparty\lib\pkgconfig"
  - qmake "CONFIG += release"
  - mingw32-make -j4
  - dir release
  - move "release\%PROGRAMNAME%.exe" "..\%OUTPUT_DIRECTORY%\%PROGRAMNAME%.exe"
  - move "..\README.md" "..\%OUTPUT_DIRECTORY%\README.md.txt"
  - rmdir /S /Q release
  - mingw32-make clean
  - qmake "CONFIG += console release"
  - mingw32-make -j4
  - dir release
  - move "release\%PROGRAMNAME%.exe" "..\%OUTPUT_DIRECTORY%\%PROGRAMNAME%_console.exe"
  - cd ..
  - 7z a -mx=9 "%OUTPUT_FILENAME%" "%OUTPUT_DIRECTORY%"
  - '%CYG_ROOT_WIN%\bin\md5sum "%OUTPUT_FILENAME%"'
  - '%CYG_ROOT_WIN%\bin\sha1sum "%OUTPUT_FILENAME%"'
  - '%CYG_ROOT_WIN%\bin\sha512sum "%OUTPUT_FILENAME%"'

artifacts:
  - path: $(OUTPUT_FILENAME)
    name: QDeviceMonitor

# vim: textwidth=0
