version: 0.0.{build}

os: unstable

install:
  - set QTDIR=C:\Qt\Qt5.3.2\5.3\mingw482_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Program Files\7-Zip

build_script:
  - cd qdevicemonitor
  - qmake
  - mingw32-make -j2
  - dir release
  - cd ..
  - dir C:\Qt\Qt5.3.2\5.3\mingw482_32
  - dir C:\Qt\Qt5.3.2\5.3\mingw482_32\lib
  - dir C:\MinGW\bin
  - dir C:\Qt
  - dir "C:\Program Files"
  - dir "C:\Program Files (x86)"
  - copy C:\MinGW\bin\libgcc_s_dw2-1.dll .
  - copy qdevicemonitor\release\qdevicemonitor.exe .
  - 7z a qdevicemonitor.7z qdevicemonitor.exe libgcc_s_dw2-1.dll

artifacts:
  - path: qdevicemonitor.7z
    name: QDeviceMonitor

#  - path: qdevicemonitor\release\qdevicemonitor.exe
#    name: QDeviceMonitor

#  - path: libgcc_s_dw2-1.dll
#    name: libgcc_s_dw2-1

#deploy:
#  provider: FTP
#  protocol: ftps
#  host: qdevicemonitor.uhostall.com
#  username: u356567517
#  password:
#    secure: tL3jXgf4CjEoLuCxc9xR/iQTD03LrZ/i7GoVmR8o2oE=
#  folder: windows
#  artifact: /.*\.exe/
