version: 0.0.{build}

os: unstable

install:
  - ci-scripts\set_env.bat
  - echo %OUTPUT_DATETIME%
  - echo %OUTPUT_DIRECTORY%
  - echo %OUTPUT_FILENAME%
  - dir C:\Qt
  - dir %QTDIR%\
  - dir %QTDIR%\lib
  - dir %QTDIR%\bin
  - dir %MINGW%\bin
  - dir "C:\Program Files"
  - dir "C:\Program Files (x86)"

build_script:
  - cd qdevicemonitor
  - qmake
  - mingw32-make -j4
  - dir release
  - cd ..
  - mkdir "%OUTPUT_DIRECTORY%"
  - cd "%OUTPUT_DIRECTORY%"
  - mkdir "platforms"
  - copy "%QTDIR%\bin\libgcc_s_dw2-1.dll" .
  - copy "%QTDIR%\bin\libstdc++-6.dll" .
  - copy "%QTDIR%\bin\libwinpthread-1.dll" .
  - copy "%QTDIR%\bin\icuin52.dll" .
  - copy "%QTDIR%\bin\icuuc52.dll" .
  - copy "%QTDIR%\bin\icudt52.dll" .
  - copy "%QTDIR%\bin\Qt5Core.dll" .
  - copy "%QTDIR%\bin\Qt5Gui.dll" .
  - copy "%QTDIR%\bin\Qt5Widgets.dll" .
  - copy "%QTDIR%\plugins\platforms\qwindows.dll" platforms\
  - move "..\qdevicemonitor\release\qdevicemonitor.exe" .
  - cd ..
  - 7z a -mx=9 "%OUTPUT_FILENAME%" "%OUTPUT_DIRECTORY%"

artifacts:
  - path: $(OUTPUT_FILENAME)
    name: QDeviceMonitor

# vim: textwidth=0
